[tool.pyright]
strict = ["*.py", "tests/*.py", "flake8_trio/**/*.py"]
exclude = ["**/node_modules", "**/__pycache__", "**/.*"]
reportUnusedCallResult=false
reportUninitializedInstanceVariable=true
reportPropertyTypeMismatch=true
reportMissingSuperCall=true
reportImplicitStringConcatenation=true
reportCallInDefaultInitializer=true
reportShadowedImports=true

[tool.codespell]
ignore-words-list = 'spawnve'
